// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/softwarepkg": {
            "get": {
                "description": "list software packages",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SoftwarePkg"
                ],
                "summary": "list software packages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "importer of the softwarePkg",
                        "name": "importer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "phase of the softwarePkg",
                        "name": "phase",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "count per page",
                        "name": "count_per_page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page num which starts from 1",
                        "name": "page_num",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.SoftwarePkgsDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "description": "apply a new software package",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SoftwarePkg"
                ],
                "summary": "apply a new software package",
                "parameters": [
                    {
                        "description": "body of applying a new software package",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.softwarePkgRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/v1/softwarepkg/{id}": {
            "get": {
                "description": "get software package",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "SoftwarePkg"
                ],
                "summary": "get software package",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of software package",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.SoftwarePkgReviewDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.SoftwarePkgApplicationDTO": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "sig": {
                    "type": "string"
                },
                "source_code": {
                    "type": "string"
                }
            }
        },
        "app.SoftwarePkgBasicInfoDTO": {
            "type": "object",
            "properties": {
                "applied_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "importer": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "pkg_name": {
                    "type": "string"
                },
                "repo_link": {
                    "type": "string"
                }
            }
        },
        "app.SoftwarePkgReviewCommentDTO": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "app.SoftwarePkgReviewDTO": {
            "type": "object",
            "properties": {
                "application": {
                    "$ref": "#/definitions/app.SoftwarePkgApplicationDTO"
                },
                "applied_at": {
                    "type": "string"
                },
                "approved_by": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.SoftwarePkgReviewCommentDTO"
                    }
                },
                "id": {
                    "type": "string"
                },
                "importer": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "pkg_name": {
                    "type": "string"
                },
                "rejected_by": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "repo_link": {
                    "type": "string"
                }
            }
        },
        "app.SoftwarePkgsDTO": {
            "type": "object",
            "properties": {
                "pkgs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.SoftwarePkgBasicInfoDTO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "controller.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "controller.softwarePkgRequest": {
            "type": "object",
            "required": [
                "package_desc",
                "package_name",
                "package_platform",
                "package_reason",
                "package_sig",
                "source_code_license",
                "source_code_url"
            ],
            "properties": {
                "package_desc": {
                    "type": "string"
                },
                "package_name": {
                    "type": "string"
                },
                "package_platform": {
                    "type": "string"
                },
                "package_reason": {
                    "type": "string"
                },
                "package_sig": {
                    "type": "string"
                },
                "source_code_license": {
                    "type": "string"
                },
                "source_code_url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
